name: Validate Pull Request

on: [pull_request]

jobs:
  build_package:
    name: Build job
    runs-on: [self-hosted, runner1]
    steps:
      - id: cleanup_workspace
        name: Cleanup workspace for the job (self hosted only)
        run: |
          rm -fr *
      - id: checkout_self
        name: Check out PR
        uses: actions/checkout@v2
        with:
          path: src 
      - id: build_and_test
        name: Build and test
        uses: ./src/.github/builder
        with:
          path: src
          coverage_threshold: 95
